//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace queries.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("queries.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Id_oceny	Data	Id_ucznia	Id_przedmiotu	Ocena
        ///1	2014-09-08	704/2014	1	2
        ///2	2014-09-08	312/2012	1	4
        ///3	2014-09-08	649/2013	3	5
        ///4	2014-09-08	228/2011	4	4
        ///5	2014-09-09	684/2013	24	5
        ///6	2014-09-10	701/2014	2	3
        ///7	2014-09-11	573/2013	20	3
        ///8	2014-09-11	876/2014	10	2
        ///9	2014-09-11	605/2013	1	5
        ///10	2014-09-12	697/2013	21	4
        ///11	2014-09-12	741/2014	6	2
        ///12	2014-09-12	522/2013	4	3
        ///13	2014-09-12	395/2012	5	3
        ///14	2014-09-12	709/2014	1	4
        ///15	2014-09-12	721/2014	17	4
        ///16	2014-09-12	582/2013	1	2
        ///17	2014-09-12	677/2013	 [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string oceny {
            get {
                return ResourceManager.GetString("oceny", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Id_przedmiotu	Nazwa_przedmiotu
        ///1	j.polski
        ///2	j.angielski
        ///3	j.niemiecki
        ///4	matematyka
        ///5	fizyka
        ///6	historia
        ///7	geografia
        ///8	biologia
        ///9	chemia
        ///10	informatyka
        ///11	wiedza o spoleczenstwie
        ///12	wiedza o kulturze
        ///13	edukacja dla bezpieczenstwa
        ///14	podstawy przedsiebiorczosci
        ///15	wychowanie fizyczne
        ///16	historia i spoleczenstwo - przedmiot uzupelniajacy
        ///17	systemy operacyjne
        ///18	urzadzenia techniki komputerowej
        ///19	diagnostyka i naprawa urzadzen techniki komputerowej
        ///20	jezyk angielski zawodowy w branzy info [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string przedmioty {
            get {
                return ResourceManager.GetString("przedmioty", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu Id_ucznia	Imie	Nazwisko	Klasa
        ///123/2011	Wojciech	Banasik	IV E
        ///124/2011	Monika	Baranowska	IV E
        ///125/2011	Janusz	Czerwinski	IV E
        ///126/2011	Sebastian	Dabrowski	IV E
        ///127/2011	Pawel	Grodzki	IV E
        ///128/2011	Michal	Hardy	IV E
        ///129/2011	Grzegorz	Henryszewski	IV E
        ///130/2011	Justyna	Kaczmarek	IV E
        ///131/2011	Mateusz	Kawicki	IV E
        ///132/2011	Maria	Konopnicka	IV E
        ///133/2011	Zygmunt	Kowalewicz	IV E
        ///134/2011	Jan	Krata	IV E
        ///135/2011	Anita	Krol	IV E
        ///136/2011	Anna	Loch	IV E
        ///137/2011	Michal	Lubanska 	IV E
        ///138/2011	Dagmara [obcięto pozostałą część ciągu]&quot;;.
        /// </summary>
        internal static string uczniowie {
            get {
                return ResourceManager.GetString("uczniowie", resourceCulture);
            }
        }
    }
}
